# Generated by Django 6.0.7 on 2026-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_projects_project_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='unknown'),
            preserve_default=False,
        ),
    ]
