# Generated by Django 6.0.7 on 2026-09-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_project_type_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(),
        ),
    ]
